### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by adamSneller** [yxonic/vite-serve#1] opened 2022-04-07 17:03 UTC
I am not able to get this to work. Here are the steps I took to install and test it. Any ideas? Thanks!

From the command line:

    npm i -g vite-serve
    npm create vite@latest

(options selected: vue, vue)

    cd test-vite-serve
    npm install
    vite-serve HelloWorld.vue

I then navigate to the page (http://localhost:3000/) and receive the following error:

> Network: use `--host` to expose
(node:74037) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'etag' of undefined
    at send$1 (/usr/local/lib/node_modules/vite-serve/node_modules/vite/dist/node/chunks/dep-611778e0.js:53809:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/vite-serve/dist/vue.js:45:48)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/vite-serve/dist/vue.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:74037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74037) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yxonic** [comment] 2022-04-08 06:28
Thanks for reporting this issue! This was due to an upstream update of vite, and was fixed in the latest release. You can try out the new version:

```sh
npm i -g vite-serve@0.4.4
```

Tell me if you experience any further issues.

**Comment by adamSneller** [comment] 2022-04-08 11:44
Thanks Yu Yin. I ran the following commands:

    npm i -g vite-serve@0.4.4
    vite-serve <MyComponent>.vue

But when I navigate to the link provided (`https:localhost:3000/`) the terminal just fills up with `^[[D`.

> Local: http://localhost:3000/
  > Network: use `--host` to expose
^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D

Any ideas?

**Comment by yxonic** [comment] 2022-04-09 03:10
I can't reproduce this problem. Can you describe your running environment? Or did you accidentally press on right arrow key or something?

**Comment by adamSneller** [comment] 2022-04-11 09:02
It looks like the last error message was on my end. However, I just spun up a new project to test and now when I run the app, I just get a blank page without any content.

Here are the steps to reproduce:

    cd ~/<development folder>
    npm create vite@latest
    
Options:

    Project name: test-vite-serve
    Select a framework: vue
    Select a variant: vue

Then

    cd test-vite-serve
    npm install
    vite-serve HelloWorld.vue

I then command-click the provided link (`http://localhost:3000/`). But all I see is a blank canvas.

Thanks,

**Comment by yxonic** [comment] 2022-04-21 13:29
I couldn't reproduce this problem. Closing this issue.

**Closed as completed by yxonic** 2022-04-21 13:29 UTC
